export const translations = {
  en: {
    nav: { home: 'Home', services: 'Services', packages: 'Tour Packages', visa: 'Visa Assistance', jobs: 'Job Vacancies' },
    hero: { title1: 'EXPLORE THE WORLD WITH', title2: 'SUNDAY INFINITY', subtitle: 'Your trusted partner for tours, visas, and global job opportunities based in Armenia.', planTrip: 'Plan Your Trip', contact: 'Contact Us' },
    search: { serviceLabel: 'Service Type', serviceOption1: 'Tour Packages', serviceOption2: 'Visa Assistance', serviceOption3: 'Job Vacancies', destinationLabel: 'Destination', destinationOption1: 'Armenia', destinationOption2: 'Georgia', destinationOption3: 'Europe', findOptions: 'Find Options' },
    services: { title: 'Our Premium Services', subtitle: 'Comprehensive travel and career solutions tailored for you', tours: 'Global Tours', toursDesc: 'Unforgettable journeys across Armenia, Georgia, Europe and beyond.', visa: 'Visa Support', visaDesc: 'Expert guidance for tourist, work, and student visas worldwide.', jobs: 'Job Placement', jobsDesc: 'Connecting talent with international career opportunities.' },
    packages: { title: 'Popular Tour Packages', subtitle: 'Discover our most requested itineraries', armenia: 'Explore Armenia', armeniaDesc: '7 Days • Yerevan, Sevan, Garni', georgia: 'Taste of Georgia', georgiaDesc: '5 Days • Tbilisi, Kazbegi', europe: 'European Highlights', europeDesc: '10 Days • Multiple Countries', bookNow: 'Book Now' },
    split: { visaTitle: 'Visa Assistance', visaFeature1: 'Schengen Visa Processing', visaFeature2: 'UAE & Middle East Visas', visaFeature3: 'Student Visa Consultation', applyVisa: 'Apply for Visa', jobTitle: 'International Jobs', jobFeature1: 'Hospitality & Tourism Roles', jobFeature2: 'Construction & Engineering', jobFeature3: 'IT & Professional Services', submitCv: 'Submit Your CV' },
    footer: { about: 'About Us', aboutText: 'Sunday Infinity Tours & Travels is your gateway to global exploration and career advancement.', quickLinks: 'Quick Links', contact: 'Contact Info', rights: '© 2026 Sunday Infinity Tours & Travels. All rights reserved.' },
    testimonials: { title: 'What Our Clients Say', subtitle: 'Real stories from real travelers' },
    faq: { title: 'Frequently Asked Questions', subtitle: 'Everything you need to know', q1: 'How long does visa processing take?', a1: 'Visa processing times vary by destination, but typically take between 2 to 4 weeks.', q2: 'Are flights included in the tour packages?', a2: 'Most of our packages exclude international flights to give you flexibility, but include all domestic transfers.', q3: 'Do I need to pay upfront for job placements?', a3: 'We offer consultation and placement services with transparent fee structures. Please contact us for specific roles.' },
    instagram: { title: 'Follow Us on Instagram', subtitle: '@sundayinfinity01' },
    modal: { details: 'Details / Message', submit: 'Submit Inquiry', name: 'Name', namePlaceholder: 'Your full name', email: 'Email', emailPlaceholder: 'Your email address', phone: 'Phone', phonePlaceholder: 'Your phone number', reqPlaceholder: 'Tell us about your requirements...' },
    testimonial: { text: '"Sunday Infinity made our trip absolutely seamless. The visa process was quick, and the tour guides were incredibly knowledgeable. Highly recommended!"', author: 'Alex Mitchell', role: 'Solo Traveler' },
    cardTags: { location: 'Location', tour: 'Tour', readMore: 'READ MORE' }
  },
  ru: {
    nav: { home: 'Главная', services: 'Услуги', packages: 'Турпакеты', visa: 'Визовая Поддержка', jobs: 'Вакансии' },
    hero: { title1: 'ИССЛЕДУЙТЕ МИР С', title2: 'SUNDAY INFINITY', subtitle: 'Ваш надежный партнер по турам, визам и трудоустройству за рубежом из Армении.', planTrip: 'Спланировать Поездку', contact: 'Связаться с Нами' },
    search: { serviceLabel: 'Тип Услуги', serviceOption1: 'Турпакеты', serviceOption2: 'Визовая Поддержка', serviceOption3: 'Вакансии', destinationLabel: 'Направление', destinationOption1: 'Армения', destinationOption2: 'Грузия', destinationOption3: 'Европа', findOptions: 'Найти Варианты' },
    services: { title: 'Наши Премиум Услуги', subtitle: 'Комплексные решения для путешествий и карьеры', tours: 'Глобальные Туры', toursDesc: 'Незабываемые путешествия по Армении, Грузии, Европе и не только.', visa: 'Визовая Поддержка', visaDesc: 'Экспертная помощь в получении туристических, рабочих и студенческих виз.', jobs: 'Трудоустройство', jobsDesc: 'Соединяем таланты с международными карьерными возможностями.' },
    packages: { title: 'Популярные Турпакеты', subtitle: 'Откройте для себя наши самые востребованные маршруты', armenia: 'Исследуйте Армению', armeniaDesc: '7 Дней • Ереван, Севан, Гарни', georgia: 'Вкус Грузии', georgiaDesc: '5 Дней • Тбилиси, Казбеги', europe: 'Лучшее в Европе', europeDesc: '10 Дней • Несколько Стран', bookNow: 'Забронировать' },
    split: { visaTitle: 'Визовая Поддержка', visaFeature1: 'Оформление Шенгенской визы', visaFeature2: 'Визы в ОАЭ и на Ближний Восток', visaFeature3: 'Консультации по студенческим визам', applyVisa: 'Подать на Визу', jobTitle: 'Работа за Рубежом', jobFeature1: 'Вакансии в сфере гостеприимства и туризма', jobFeature2: 'Строительство и инженерия', jobFeature3: 'ИТ и профессиональные услуги', submitCv: 'Отправить Резюме' },
    footer: { about: 'О Нас', aboutText: 'Sunday Infinity Tours & Travels - ваш путь к глобальным исследованиям и карьерному росту.', quickLinks: 'Быстрые Ссылки', contact: 'Контакты', rights: '© 2026 Sunday Infinity Tours & Travels. Все права защищены.' },
    testimonials: { title: 'Что говорят наши клиенты', subtitle: 'Реальные истории реальных путешественников' },
    faq: { title: 'Часто Задаваемые Вопросы', subtitle: 'Все, что вам нужно знать', q1: 'Сколько времени занимает оформление визы?', a1: 'Время оформления визы зависит от страны, но обычно составляет от 2 до 4 недель.', q2: 'Включены ли авиабилеты в турпакеты?', a2: 'Большинство наших пакетов не включают международные перелеты для гибкости, но включают все внутренние трансферы.', q3: 'Нужно ли платить заранее за трудоустройство?', a3: 'Мы предлагаем консультации и услуги по трудоустройству с прозрачной структурой оплаты. Пожалуйста, свяжитесь с нами для уточнения деталей.' },
    instagram: { title: 'Следите за нами в Instagram', subtitle: '@sundayinfinity01' },
    modal: { details: 'Детали / Сообщение', submit: 'Отправить Запрос', name: 'Имя', namePlaceholder: 'Ваше полное имя', email: 'Email', emailPlaceholder: 'Ваш Email', phone: 'Телефон', phonePlaceholder: 'Ваш номер телефона', reqPlaceholder: 'Расскажите о ваших требованиях...' },
    testimonial: { text: '"Sunday Infinity сделала нашу поездку абсолютно безупречной. Процесс получения визы прошел быстро, а гиды были невероятно компетентны. Очень рекомендую!"', author: 'Алекс Митчелл', role: 'Путешественник' },
    cardTags: { location: 'Локация', tour: 'Тур', readMore: 'ПОДРОБНЕЕ' }
  },
  am: {
    nav: { home: 'Գլխավոր', services: 'Ծառայություններ', packages: 'Տուր Փաթեթներ', visa: 'Վիզայի Աջակցություն', jobs: 'Թափուր Աշխատատեղեր' },
    hero: { title1: 'ԲԱՑԱՀԱՅՏԵՔ ԱՇԽԱՐՀԸ', title2: 'SUNDAY INFINITY-Ի ՀԵՏ', subtitle: 'Ձեր վստահելի գործընկերը տուրերի, վիզաների և արտերկրում աշխատանքի համար Հայաստանից:', planTrip: 'Պլանավորեք Ձեր Ուղևորությունը', contact: 'Կապվել Մեզ Հետ' },
    search: { serviceLabel: 'Ծառայության Տեսակ', serviceOption1: 'Տուր Փաթեթներ', serviceOption2: 'Վիզայի Աջակցություն', serviceOption3: 'Թափուր Աշխատատեղեր', destinationLabel: 'Ուղղություն', destinationOption1: 'Հայաստան', destinationOption2: 'Վրաստան', destinationOption3: 'Եվրոպա', findOptions: 'Գտնել Տարբերակներ' },
    services: { title: 'Մեր Պրեմիում Ծառայությունները', subtitle: 'Համապարփակ լուծումներ ճանապարհորդության և կարիերայի համար', tours: 'Գլոբալ Տուրեր', toursDesc: 'Անմոռանալի ճանապարհորդություններ Հայաստանում, Վրաստանում, Եվրոպայում և այլուր:', visa: 'Վիզայի Աջակցություն', visaDesc: 'Փորձագիտական օգնություն տուրիստական, աշխատանքային և ուսանողական վիզաների համար:', jobs: 'Աշխատանքի Տեղավորում', jobsDesc: 'Կապելով տաղանդները միջազգային կարիերայի հնարավորությունների հետ:' },
    packages: { title: 'Հայտնի Տուր Փաթեթներ', subtitle: 'Բացահայտեք մեր ամենապահանջված երթուղիները', armenia: 'Բացահայտեք Հայաստանը', armeniaDesc: '7 Օր • Երևան, Սևան, Գառնի', georgia: 'Վրաստանի Համը', georgiaDesc: '5 Օր • Թբիլիսի, Կազբեգի', europe: 'Եվրոպական Լավագույնը', europeDesc: '10 Օր • Մի քանի Երկրներ', bookNow: 'Ամրագրել' },
    split: { visaTitle: 'Վիզայի Աջակցություն', visaFeature1: 'Շենգեն վիզայի ձևակերպում', visaFeature2: 'ԱՄԷ և Մերձավոր Արևելքի վիզաներ', visaFeature3: 'Ուսանողական վիզայի խորհրդատվություն', applyVisa: 'Դիմել Վիզայի Համար', jobTitle: 'Միջազգային Աշխատանք', jobFeature1: 'Հյուրանոցային և տուրիզմի ոլորտ', jobFeature2: 'Շինարարություն և ինժեներիա', jobFeature3: 'ՏՏ և պրոֆեսիոնալ ծառայություններ', submitCv: 'Ուղարկել Ռեզյումեն' },
    footer: { about: 'Մեր Մասին', aboutText: 'Sunday Infinity Tours & Travels-ը ձեր ուղին է դեպի գլոբալ բացահայտումներ և կարիերայի աճ:', quickLinks: 'Արագ Հղումներ', contact: 'Կոնտակտներ', rights: '© 2026 Sunday Infinity Tours & Travels: Բոլոր իրավունքները պաշտպանված են:' },
    testimonials: { title: 'Ինչ են ասում մեր հաճախորդները', subtitle: 'Իրական պատմություններ իրական ճանապարհորդներից' },
    faq: { title: 'Հաճախ Տրվող Հարցեր', subtitle: 'Այն ամենը, ինչ ձեզ հարկավոր է իմանալ', q1: 'Որքա՞ն է տևում վիզայի ձևակերպումը:', a1: 'Վիզայի մշակման ժամանակը կախված է երկրից, բայց սովորաբար տևում է 2-ից 4 շաբաթ:', q2: 'Արդյո՞ք ավիատոմսերը ներառված են տուր փաթեթներում:', a2: 'Մեր փաթեթների մեծ մասը չի ներառում միջազգային թռիչքներ՝ ձեզ ճկունություն տալու համար, բայց ներառում են բոլոր ներքին տրանսֆերները:', q3: 'Արդյո՞ք պետք է նախապես վճարել աշխատանքի տեղավորման համար:', a3: 'Մենք առաջարկում ենք խորհրդատվություն և աշխատանքի տեղավորման ծառայություններ՝ թափանցիկ վճարային համակարգով: Խնդրում ենք կապվել մեզ հետ մանրամասների համար:' },
    instagram: { title: 'Հետևեք մեզ Instagram-ում', subtitle: '@sundayinfinity01' },
    modal: { details: 'Մանրամասներ / Հաղորդագրություն', submit: 'Ուղարկել Հարցում', name: 'Անուն', namePlaceholder: 'Ձեր լրիվ անունը', email: 'Էլ. փոստ', emailPlaceholder: 'Ձեր էլ. փոստը', phone: 'Հեռախոս', phonePlaceholder: 'Ձեր հեռախոսահամարը', reqPlaceholder: 'Պատմեք մեզ ձեր պահանջների մասին...' },
    testimonial: { text: '"Sunday Infinity-ն մեր ուղևորությունը դարձրեց անթերի: Վիզայի գործընթացը արագ էր, իսկ զբոսավարները չափազանց բանիմաց էին: Խիստ խորհուրդ ենք տալիս:"', author: 'Ալեքս Միտչել', role: 'Ճանապարհորդ' },
    cardTags: { location: 'Տեղանք', tour: 'Տուր', readMore: 'ԿԱՐԴԱԼ ԱՎԵԼԻՆ' }
  }
};
